### ISSUE TITLE
JSMSimMovement - Helicopters not supported. Unreal Engine

### ISSUE THREAD

**Issue by Numfundle** [JSBSim-Team/jsbsim#662] opened 2022-06-17 13:12 UTC
Helicopters like ah1s are not supported. I think this is due to incomplete implementation of the Unreal component around propulsion.

When starting a reference application with the "ah1s" model and engines running, EngineRPM simply ticks down and thrust rapidly drops off.

**Comment by seanmcleod** [comment] 2022-06-17 13:59
Take a look at the following discussion that was started a couple of days ago - https://github.com/JSBSim-Team/jsbsim/discussions/659

**Comment by bcoconni** [comment] 2022-06-17 17:48
This issue is a duplicate of #660 which is itself a duplicate of #656. Please check that an issue has not already been submitted before opening a new one.

This issue is closed as a duplicate.

**Closed by bcoconni** 2022-06-17 17:48 UTC
