### ISSUE TITLE
UJSBSimMovementComponent can't correct display debug draw aircraft parts when user modified Structural Frame Origin

### ISSUE THREAD

**Issue by thorcx** [JSBSim-Team/jsbsim#637] opened 2022-06-01 13:50 UTC
Hi, I'm use this wonderful plugin for simulation, i create a Pawn in c++, in the pawn i created a UJSBSimMovementComponent.
After that, i create a blueprint pawn inherited from that c++ Pawn class. Then in the child blueprint's details panel, i try to adjust the structural frame origin, and expect to see the debug draw aircraft main parts dots change in the Viewport panel, but it won't show any position changes in that Blueprint's viewport, but if i create the UJSBSimMovementComponent in Blueprint and change the structural frame origin, it will work as expected.I guess this is a bug.

I'm using UE5.0.2, vs2019 ,win10, JSBSimFlightDynamicsModel v1.0

**Comment by bcoconni** [comment] 2022-06-11 10:04
@thorcx this bug should now be fixed in the `master` branch, following @AlbanBERGERET-Epic's PR #652. Could you please check and confirm if the plugin now works as expected ?

Thanks.

**Comment by bcoconni** [comment] 2022-06-19 10:25
The problem reported in this issue is now considered fixed and the issue is closed.

**Closed by bcoconni** 2022-06-19 10:25 UTC
Labels: bug, Unreal Engine
