### ISSUE TITLE
Brakes and static force

### ISSUE THREAD

**Issue by legoboyvdlp** [JSBSim-Team/jsbsim#130] opened 2018-11-06 11:13 UTC
Hi,
Many users are tuning brakes using <static_friction> - this results in correct braking behaviour, but really seems to mess up steering - is it possible to have a property that tunes the brake force without affecting the static friction of the wheels ( resistance to lateral force if I remember right? )

**Comment by bcoconni** [comment] 2018-11-06 22:43
@legoboyvdlp 
This topic is currently being discussed in the issue #127.
Thanks to post your comments/question in that other issue.

This topic is closed as a duplicate of #127.

**Closed by bcoconni** 2018-11-06 22:43 UTC
Labels: duplicate

**Comment by legoboyvdlp** [comment] 2018-11-07 10:17
Thanks!
