### ISSUE TITLE
Make Python tests build for Windows users

### ISSUE THREAD

**Issue by agodemar** [JSBSim-Team/jsbsim#14] opened 2018-04-30 08:24 UTC
It should be smooth enough for Windows users to build the Python/Cython part of JSBSim that produces tests. Instructions for those who have Anaconda or similar environments installed would be nice.

**Comment by seanmcleod** [comment] 2018-04-30 08:57
Recently when I tested the cmake support in Visual Studio 2017 I built the JSBSim python module without any major issues. In my case I have a 64bit version of Python 3.5 installed via Ananconda.

One minor issue was that I couldn't build a debug version of the Python module, the linker was looking for a debug version of python DLL and my system doesn't have the debug version installed. So I simply built the release version without any issues.

One other minor issue was some trivial Python 2 versus 3 difference in one of the python test files. I didn't spend too much more time testing that all the python tests ran successfully. I'll get round to testing it some more in the near future.

**Comment by bcoconni** [comment] 2018-04-30 10:25
@seanmcleod Could you please provide some details about the way you proceeded to build the Python module with VS2017 ? I could then add them to `README.md`

The incompatibility of the test code with Python 3 does not come as a surprise since I cannot install Cyhton for Python 3 on my computer. I have toyed too much with the Python modules upgrade from 2 different sources (Fedora package manager and pip) and reached a point where some things are broken. Once Fedora 28 will be released I will make a clean install that should hopefully fix that.

**Comment by agodemar** [comment] 2018-04-30 10:43
@seanmcleod Having a couple of screenshots would be nice. I would put them into the JSBSim manual as well.

**Comment by agodemar** [comment] 2018-04-30 13:25
@seanmcleod Since this is more like a user manual thing, I'd say you can put the screenshots here: [JSBSim-Team/jsbsim-reference-manual/tree/master/docs/assets/img](https://github.com/JSBSim-Team/jsbsim-reference-manual/tree/master/docs/assets/img)
We have how-to-build section in the manual as well.

**Comment by seanmcleod** [comment] 2018-05-01 15:52
@bcoconni I've submitted a pull request for Agostino to take a look at in terms of more detailed documentation on using Visual Studio for building JSBSim etc. using the CMake support etc. Once it's merged and published take a look. Maybe we should put a link in the JSBSim readme.md pointing to this documentation page for more details on Visual Studio building options rather than repeating the details in the JSBSim readme.md.

**Comment by agodemar** [comment] 2018-05-01 16:50
I've merged adapted Sean's updates. Here are the links:

- Building the program [https://jsbsim-team.github.io/jsbsim-reference-manual/mypages/building-the-program](https://jsbsim-team.github.io/jsbsim-reference-manual/mypages/building-the-program/)

- Building with Visual Studio [https://jsbsim-team.github.io/jsbsim-reference-manual/mypages/building-using-visualstudio/](https://jsbsim-team.github.io/jsbsim-reference-manual/mypages/building-using-visualstudio/)

**Comment by bcoconni** [comment] 2018-05-27 23:00
This issue is now a duplicate of #35.
Issue closed and discussion will continue in #35.

**Closed by bcoconni** 2018-05-27 23:00 UTC
Labels: Python, documentation, duplicate, enhancement
