### ISSUE TITLE
Build JSBSim by VS2019 and use C++ API

### ISSUE THREAD

**Issue by DreamerSurpass** [JSBSim-Team/jsbsim#888] opened 2023-04-11 15:12 UTC
Hello,

I use VS2019 to build JSBSim and try to use C++ API to interface with JSBSim just like tutorial code
`#include <FGFDMExec.h>

int main(int argc, char **argv)
{
  JSBSim::FGFDMExec FDMExec;
  FDMExec.LoadScript(SGPath(argv[1]));
  FDMExec.RunIC();
  bool result = true;
  while (result) result = FDMExec.Run();
}`

I also added the JSBSim.lib and src path, but failed to run.
![image](https://user-images.githubusercontent.com/93421761/231206586-1b3b73b6-7927-4b8c-a18a-0fe5647aaa6f.png)

I'm not sure is this a bug and how to fix it. I use Windows 10, VS2019, C++ language.

**Comment by bcoconni** [comment] 2023-04-11 19:54
@DreamerSurpass this issue is a duplicate of the discussion #887 that you have opened a few hours ago.
In addition, this has nothing to do with a bug nor a is it a feature request so this issue is closed and the topic shall be continued in discussion #887.
Thanks.

**Closed by bcoconni** 2023-04-11 19:54 UTC
